import test from 'node:test';
import assert from 'node:assert/strict';
import { VIN } from '../src/core.js';
import { running, config, redirectUri, scope } from './helpers.js';
test('consent, single-use code, redirect binding, refresh rotation and revocation', async t => {
  const a = await running(t);
  const denied = await a.authorize('deny'); assert.equal(denied.searchParams.get('error'), 'access_denied');
  assert.equal(a.garage.granted, false);
  const url = await a.authorize(); const code = url.searchParams.get('code');
  assert.equal(url.searchParams.get('state'), 'test-state');
  const token = await (await a.exchange(code)).json();
  assert.equal((await a.exchange(code)).status, 400);
  const rotated = await (await a.request(a.api, '/oauth2/v3/token', { grant_type: 'refresh_token', refresh_token: token.refresh_token, client_id: 'sandbox-client' })).json();
  assert.notEqual(rotated.refresh_token, token.refresh_token);
  assert.equal((await a.request(a.api, '/oauth2/v3/token', { grant_type: 'refresh_token', refresh_token: token.refresh_token, client_id: 'sandbox-client' })).status, 400);
  await a.request(a.control, '/control/revoke');
  assert.equal((await a.request(a.api, '/api/1/vehicles', {}, rotated.access_token, 'GET')).status, 401);
  const invalid = await fetch(`${a.api}/oauth2/v3/authorize?${new URLSearchParams({ client_id:'sandbox-client', redirect_uri: redirectUri + '/wrong', state:'x', scope, response_type:'code' })}`);
  assert.equal(invalid.status, 400);
});
test('onboard, pair, configure, drive, inject faults, replay, delete and reset over HTTP', async t => {
  const received = [];
  const a = await running(t, { send: async p => received.push(structuredClone(p)) });
  const token = (await a.login()).access_token;
  const call = (path, data, method) => a.request(a.api, path, data, token, method);
  assert.equal((await call('/api/1/vehicles', {}, 'GET')).status, 200);
  assert.equal((await call('/api/1/vehicles/unknown/vehicle_data', {}, 'GET')).status, 404);
  const c = config(a.garage.snapshot().now);
  let r = await (await call('/api/1/vehicles/fleet_telemetry_config', { vins:[VIN], config:c })).json();
  assert.equal(r.response.updated_vehicles, 0);
  await a.request(a.control, '/control/pair', { paired:true });
  r = await (await call('/api/1/vehicles/fleet_status', { vins:[VIN] })).json();
  assert.deepEqual(r.response.key_paired_vins, [VIN]);
  assert.equal((await call('/api/1/vehicles/fleet_telemetry_config', { vins:[VIN], config:{ ...c, hostname:'example.com' } })).status, 400);
  assert.equal((await call('/api/1/vehicles/fleet_telemetry_config', { vins:[VIN], config:c })).status, 200);
  assert.equal(received.length, 0);
  await a.request(a.control, '/control/drive', { speedKmh:36 });
  await a.request(a.control, '/control/faults', { delaySeconds:30, copies:2 });
  await a.request(a.control, '/control/advance', { seconds:1 }); assert.equal(received.length, 0);
  await a.request(a.control, '/control/advance', { seconds:30 }); assert.equal(received.length, 2);
  assert.equal(received[0].createdAt, received[1].createdAt); assert.equal(received[1].isResend, true);
  await a.request(a.control, '/control/replay', { id:0 }); assert.equal(received.length, 3);
  assert.equal((await call(`/api/1/vehicles/${VIN}/fleet_telemetry_config`, [], 'DELETE')).status, 200);
  const count = a.garage.records.length;
  await a.request(a.control, '/control/advance', { seconds:30 }); assert.equal(a.garage.records.length, count);
  assert.equal((await a.request(a.api, '/control/reset')).status, 401);
  await a.request(a.control, '/control/reset'); assert.equal(a.garage.records.length, 0);
  assert.equal((await call('/api/1/vehicles', {}, 'GET')).status, 401);
});
test('access tokens expire with simulation time and disconnected delivery can recover', async t => {
  const received = []; const a = await running(t, { send: async p => received.push(p) });
  const token = (await a.login()).access_token;
  a.garage.paired = true; a.garage.configure(config(a.garage.snapshot().now));
  await a.request(a.control, '/control/faults', { disconnected:true });
  await a.request(a.control, '/control/advance', { seconds:1 }); assert.equal(received.length, 0);
  await a.request(a.control, '/control/faults', { disconnected:false });
  await a.request(a.control, '/control/advance', { seconds:0 }); assert.equal(received.length, 1);
  await a.request(a.control, '/control/advance', { seconds:3600 });
  assert.equal((await a.request(a.api, '/api/1/vehicles', {}, token, 'GET')).status, 401);
  const res = await fetch(a.control + '/control/reset', { method:'POST', headers:{origin:'http://evil.example', 'content-type':'application/json'}, body:'{}' });
  assert.equal(res.status, 403);
});
test('delivery failure retains observation for retry without advancing or rewriting time', async t => {
  let failing = true; const deliveries = [];
  const a = await running(t, { send:async payload => { if (failing) throw new Error('offline'); deliveries.push(payload); } });
  a.garage.granted = true; a.garage.paired = true; a.garage.configure(config(a.garage.snapshot().now));
  const failed = await a.request(a.control, '/control/advance', { seconds:1 });
  assert.equal(failed.status, 502);
  const timestamp = a.garage.records[0].payload.createdAt;
  assert.equal(a.garage.records[0].delivered, 0);
  failing = false;
  assert.equal((await a.request(a.control, '/control/advance', { seconds:0 })).status, 200);
  assert.equal(a.garage.records.length, 1); assert.equal(a.garage.records[0].delivered, 1);
  assert.equal(deliveries[0].createdAt, timestamp);
  for (const value of [null, [], 3, 'wrong']) {
    const r = await fetch(a.control + '/control/reset', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify(value) });
    assert.equal(r.status, 400);
  }
  assert.equal(a.garage.records.length, 1);
});
